## 1 EDA

In [15]:
import pandas as pd
ruta = "../data/processed/default of credit card clients.xls"
df_raw = pd.read_excel(ruta, header=None)
df_raw.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,NaN,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
1,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
2,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
3,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
4,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0

In [16]:
#Organizar los nombres de las columnas
df = df_raw.iloc[1:].copy()
df.columns = df.iloc[0]
df = df.iloc[1:].reset_index(drop=True)     #Eliminar las fila que contiene los nombres de las columnas 
df.head()

1,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [17]:
#Validar cantidad de filas y columnas
df.shape

(30000, 25)

In [18]:
#Validar tipos de datos: Pandas esta interpretando todos los datos como objetos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  object
 1   LIMIT_BAL                   30000 non-null  object
 2   SEX                         30000 non-null  object
 3   EDUCATION                   30000 non-null  object
 4   MARRIAGE                    30000 non-null  object
 5   AGE                         30000 non-null  object
 6   PAY_0                       30000 non-null  object
 7   PAY_2                       30000 non-null  object
 8   PAY_3                       30000 non-null  object
 9   PAY_4                       30000 non-null  object
 10  PAY_5                       30000 non-null  object
 11  PAY_6                       30000 non-null  object
 12  BILL_AMT1                   30000 non-null  object
 13  BILL_AMT2                   30000 non-null  object
 14  BILL_AMT3                   30000 non-null  object
 15  BILL_AMT4                   30000 non-null  object
 16  BILL_AMT5                   30000 non-null  object
 17  BILL_AMT6                   30000 non-null  object
 18  PAY_AMT1                    30000 non-null  object
 19  PAY_AMT2                    30000 non-null  object
 20  PAY_AMT3                    30000 non-null  object
 21  PAY_AMT4                    30000 non-null  object
 22  PAY_AMT5                    30000 non-null  object
 23  PAY_AMT6                    30000 non-null  object
 24  default payment next month  30000 non-null  object
dtypes: object(25)
memory usage: 5.7+ MB

En este conjunto de datos en particular, las 25 columnas representan valores numericos.

In [ ]:
#Convertir todas las columnas a numericas
df = df.apply(pd.to_numeric, errors="coerce")     #coerce pone los valores en Nan de los datos que no puede convertir
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_AMT3                   30000 non-null  int64
 15  BILL_AMT4                   30000 non-null  int64
 16  BILL_AMT5                   30000 non-null  int64
 17  BILL_AMT6                   30000 non-null  int64
 18  PAY_AMT1                    30000 non-null  int64
 19  PAY_AMT2                    30000 non-null  int64
 20  PAY_AMT3                    30000 non-null  int64
 21  PAY_AMT4                    30000 non-null  int64
 22  PAY_AMT5                    30000 non-null  int64
 23  PAY_AMT6                    30000 non-null  int64
 24  default payment next month  30000 non-null  int64
dtypes: int64(25)
memory usage: 5.7 MB

In [20]:
#Revisar valores que no son numericos
df.isna().sum()

1
ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

In [22]:
#Validar si hay clientes duplicados
df.duplicated().sum()

np.int64(0)

In [23]:
#Validar si hay clientes duplicados sin tener en cuenta el ID
df.drop(columns=["ID"]).duplicated().sum()

np.int64(35)

Existen 35 filas que coinciden con otros registros en todas las columas, excepto ID. Aun no se elimina estos registros, dos clientes diferentes podrian tener la misma información.

In [24]:
#Detallar los registros duplicados
duplicados = df[df.drop(columns=["ID"]).duplicated(keep=False)]
duplicados.sort_values(by=df.columns[1:].tolist())

1,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
12430,12431,20000,1,2,2,24,2,2,4,4,...,1650,1650,1650,0,0,0,0,0,0,1
14294,14295,20000,1,2,2,24,2,2,4,4,...,1650,1650,1650,0,0,0,0,0,0,1
1759,1760,50000,1,2,2,26,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
10250,10251,50000,1,2,2,26,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
7170,7171,50000,2,1,2,23,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27966,27967,360000,2,1,2,27,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
18325,18326,360000,2,1,2,29,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
22162,22163,360000,2,1,2,29,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
839,840,500000,1,1,1,43,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,1
7319,7320,500000,1,1,1,43,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
#Eliminar informacion duplicada
df = df.drop_duplicates(subset=df.columns.drop("ID"))

In [33]:
df.shape

(29965, 25)

In [ ]:
#Validar valores unicos de la base: 
df.nunique().sort_values()

1
SEX                               2
default payment next month        2
MARRIAGE                          4
EDUCATION                         7
PAY_5                            10
PAY_6                            10
PAY_2                            11
PAY_4                            11
PAY_3                            11
PAY_0                            11
AGE                              56
LIMIT_BAL                        81
PAY_AMT5                       6897
PAY_AMT4                       6937
PAY_AMT6                       6939
PAY_AMT3                       7518
PAY_AMT2                       7899
PAY_AMT1                       7943
BILL_AMT6                     20604
BILL_AMT5                     21010
BILL_AMT4                     21548
BILL_AMT3                     22026
BILL_AMT2                     22346
BILL_AMT1                     22723
ID                            29965
dtype: int64

Education: Debe tener los estados: 1 = posgrado; 2 = universidad; 3 = educación secundaria; 4 = otros. En la base tenemos mas estados.

Marriage: Debe tener 1 = casado/a; 2 = soltero/a; 3 = otros y tenemos 4 en la base.

In [ ]:
#Validando cantidad de datos en estados no identificados
df["EDUCATION"].value_counts().sort_index()

EDUCATION
0       14
1    10563
2    14019
3     4915
4      123
5      280
6       51
Name: count, dtype: int64

In [ ]:
#Total de estados desconocidos en educación
(~df["EDUCATION"].isin([1, 2, 3, 4])).sum()

np.int64(345)

In [39]:
#Reemplazar los valores de 0, 5 y 6 a 4
df["EDUCATION"] = df["EDUCATION"].replace({
    0: 4,
    5: 4,
    6: 4
})

In [ ]:
#Validando que en Educacion solo queden 4 estados
df["EDUCATION"].value_counts().sort_index()

EDUCATION
1    10563
2    14019
3     4915
4      468
Name: count, dtype: int64

In [42]:
#Validando estados de Marriage
df["MARRIAGE"].value_counts().sort_index()

MARRIAGE
0       54
1    13643
2    15945
3      323
Name: count, dtype: int64

Ingresamos los datos del estado 0 a estado 3 "otros"

In [43]:
#Reemplazar los valores de 0 a 3
df["MARRIAGE"] = df["MARRIAGE"].replace({
    0: 3,
})

In [44]:
df["MARRIAGE"].value_counts().sort_index()

MARRIAGE
1    13643
2    15945
3      377
Name: count, dtype: int64

In [ ]:
#Validando valores negativos
(df.select_dtypes(include="number") < 0).sum()

1
ID                                0
LIMIT_BAL                         0
SEX                               0
EDUCATION                         0
MARRIAGE                          0
AGE                               0
PAY_0                          8432
PAY_2                          9798
PAY_3                          9989
PAY_4                         10001
PAY_5                         10051
PAY_6                         10601
BILL_AMT1                       590
BILL_AMT2                       669
BILL_AMT3                       655
BILL_AMT4                       675
BILL_AMT5                       655
BILL_AMT6                       688
PAY_AMT1                          0
PAY_AMT2                          0
PAY_AMT3                          0
PAY_AMT4                          0
PAY_AMT5                          0
PAY_AMT6                          0
default payment next month        0
dtype: int64

In [45]:
# ---------------------------------------------------------------
# 2. RENOMBRAR columnas (consistencia: PAY_0 -> PAY_1 y nombre del target)
# ---------------------------------------------------------------
df = df.rename(columns={
    "PAY_0": "PAY_1",
    "default payment next month": "DEFAULT",
})
# Orden temporal: 1 = sept-2005 (más reciente) ... 6 = abr-2005 (más antiguo)
PAY = [f"PAY_{i}" for i in range(1, 7)]
BILL = [f"BILL_AMT{i}" for i in range(1, 7)]
PAYAMT = [f"PAY_AMT{i}" for i in range(1, 7)]

In [47]:
# ---------------------------------------------------------------
# 3. CHEQUEOS BÁSICOS
# ---------------------------------------------------------------
print("Nulos totales:", df.isna().sum().sum())
print("ID único:", df["ID"].is_unique)
print("Filas idénticas ignorando ID:", df.drop(columns="ID").duplicated().sum())

Nulos totales: 0
ID único: True
Filas idénticas ignorando ID: 0

In [48]:
# PAY_1..PAY_6
#   Oficial (UCI / Yeh & Lien 2009): -1 = pagó a tiempo; 1..9 = meses de atraso.
#   NO documentados: -2 y 0. Interpretación apoyada en los propios datos:
#     -2 -> sin consumo (saldo ~0, uso del cupo ~0%)
#     -1 -> pagó el total (el pago siguiente cubre el saldo en ~98% de casos)
#      0 -> crédito rotativo, pago parcial (uso del cupo ~62%, cubre saldo ~2%)
#   Decisión: NO son nulos ni errores -> se conservan las originales y se
#   separan en dos variables: ESTADO (categórica) y MORA (numérica).
ESTADOS = {-2: "sin_consumo", -1: "pago_total", 0: "rotativo"}
for c in PAY:
    df[f"{c}_MORA"] = df[c].clip(lower=0)                         # meses de atraso
    df[f"{c}_ESTADO"] = df[c].map(ESTADOS).fillna("mora").astype("category")

# Variables resumen del historial (suelen predecir mejor que cada mes suelto)
df["MORA_MAX"] = df[[f"{c}_MORA" for c in PAY]].max(axis=1)
df["MESES_EN_MORA"] = (df[PAY] > 0).sum(axis=1)
df["MESES_SIN_CONSUMO"] = (df[PAY] == -2).sum(axis=1)
df["MESES_ROTATIVO"] = (df[PAY] == 0).sum(axis=1)

In [49]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'DEFAULT',
       'PAY_1_MORA', 'PAY_1_ESTADO', 'PAY_2_MORA', 'PAY_2_ESTADO',
       'PAY_3_MORA', 'PAY_3_ESTADO', 'PAY_4_MORA', 'PAY_4_ESTADO',
       'PAY_5_MORA', 'PAY_5_ESTADO', 'PAY_6_MORA', 'PAY_6_ESTADO', 'MORA_MAX',
       'MESES_EN_MORA', 'MESES_SIN_CONSUMO', 'MESES_ROTATIVO'],
      dtype='str', name=1)

In [50]:
df.head(10)

1,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,PAY_4_MORA,PAY_4_ESTADO,PAY_5_MORA,PAY_5_ESTADO,PAY_6_MORA,PAY_6_ESTADO,MORA_MAX,MESES_EN_MORA,MESES_SIN_CONSUMO,MESES_ROTATIVO
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,pago_total,0,sin_consumo,0,sin_consumo,2,2,2,0
1,2,120000,2,2,2,26,-1,2,0,0,...,0,rotativo,0,rotativo,2,mora,2,2,0,3
2,3,90000,2,2,2,34,0,0,0,0,...,0,rotativo,0,rotativo,0,rotativo,0,0,0,6
3,4,50000,2,2,1,37,0,0,0,0,...,0,rotativo,0,rotativo,0,rotativo,0,0,0,6
4,5,50000,1,2,1,57,-1,0,-1,0,...,0,rotativo,0,rotativo,0,rotativo,0,0,0,4
5,6,50000,1,1,2,37,0,0,0,0,...,0,rotativo,0,rotativo,0,rotativo,0,0,0,6
6,7,500000,1,1,2,29,0,0,0,0,...,0,rotativo,0,rotativo,0,rotativo,0,0,0,6
7,8,100000,2,2,2,23,0,-1,-1,0,...,0,rotativo,0,rotativo,0,pago_total,0,0,0,3
8,9,140000,2,3,1,28,0,0,2,0,...,0,rotativo,0,rotativo,0,rotativo,2,1,0,5
9,10,20000,1,3,2,35,-2,-2,-2,-2,...,0,sin_consumo,0,pago_total,0,pago_total,0,0,4,0

In [51]:
# 5. VALIDACIONES DE RANGO / LÓGICA DE NEGOCIO (se marcan, no se borran)
# ---------------------------------------------------------------
df["FLAG_SALDO_NEGATIVO"] = (df[BILL] < 0).any(axis=1).astype(int)    # saldo a favor del cliente
df["FLAG_SOBRECUPO"] = (df["BILL_AMT1"] > df["LIMIT_BAL"]).astype(int) # deuda > cupo
df["FLAG_SIN_ACTIVIDAD"] = ((df[BILL] == 0).all(axis=1) &
                            (df[PAYAMT] == 0).all(axis=1)).astype(int)
assert df["AGE"].between(18, 100).all()
assert (df["LIMIT_BAL"] > 0).all()
assert (df[PAYAMT] >= 0).all().all()